[package]
name = "mini-db"
version = "0.1.0"
edition = "2021"

[dependencies]
fs4 = "0.13.1"
hex = "0.4.3"
lazy_static = "1.5.0"
notify = "8.1.0"
serde = { version = "1.0.217", features = ["derive"] }
sha3 = "0.10.8"
toml = "0.9.2"
tsid = "0.3.1"
